module.exports = {
  COMPETITION_ID: 72,
  SPIKE_THRESHOLD: 3,
  BASELINE_WINDOW: 30,
  VERIFICATION_TIMEOUT: 300000,
  CLOCK_SANITY_LIMIT: 300,
  MIN_SPIKE_DELTA: 500,
  POLL_INTERVAL: 10000,
  PORT: process.env.PORT || 3000,
  SOLANA_RPC: 'https://api.mainnet-beta.solana.com',
  LEDGER_FILE: './data/ledger.json',
  MARKET_TYPES: [
    'OVERUNDER_PARTICIPANT_GOALS',
    '1X2_PARTICIPANT_RESULT',
    'ASIANHANDICAP_PARTICIPANT_GOALS'
  ]
};
